In [24]:
import numpy as np

In [25]:
i = np.array([5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [26]:
i

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [27]:
j = i[1:5]

In [28]:
j[:]

array([10, 15, 20, 25])

In [29]:
j[:] = 100

In [30]:
i

array([  5, 100, 100, 100, 100,  30,  35,  40,  45,  50])